name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, my-website-prod]

    steps:
      - name: Deploy my website
        run: /srv/scripts/deploy/my-website-deploy.sh
